# Writing Tools (the Windows & Linux version) is developed and maintained by Jesai Tarun with the help of awesome contributors.
# If you've found value in Writing Tools, your support would mean the world and would help me continue active development. Thank you!

buy_me_a_coffee: jesaitarun
